services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./service-account.json:/var/www/html/service-account.json
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Admin#25
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
      image: 'phpmyadmin/phpmyadmin:latest'
      ports:
          - '81:80'
      environment:
          PMA_HOST: db
          MYSQL_ROOT_PASSWORD: root
          PMA_USER: Admin
          PMA_PASSWORD: Admin#25
      depends_on:
          - db

volumes:
  db_data:
